packages:
  - "."
overrides:
  zod: 4.4.3
  lodash: 4.18.1
allowBuilds:
  "@medusajs/telemetry": false
  "@swc/core": true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
